### ISSUE TITLE
Manafacturers datatable does not have a working search button

### ISSUE THREAD

**Issue by zenazmuth** [dan-hill/jabberfire-client#31]
Click on users drop-down menu for manufacturers, create new account, press search button.

#### Environment

**Resolution:** 1920x1080
**Device:** PC
**Operating System:** Windows 8.1
**Browser:** Firefox Version 37.0.1

**Comment by dan-hill** [comment]
The search does filtering as you type instead of waiting for a button to be clicked. I think this will be easier to see once it has been populated with a bit more data.
